{{- if .Values.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic.configmapName" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
    {{- with .Values.configmap.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.configmap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.configmap.data }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- with .Values.configmap.binaryData }}
binaryData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end -}}
